### ISSUE TITLE
Ajout des commandes anglaises dans la documentation française et vice-versa ? Plus quelques autres remarques sur la documentation

### ISSUE THREAD

**Issue by quark67** [cpierquet/thematicpuzzle#1]
Si un francophone trouve quelque part un code contenant `\usepackage{thematicpuzzle}` et cherche à connaître la syntaxe de la commande `\ThematicPuzzle` (qu'il a vu dans le même code) il risque d'être pris au dépourvu en ne voyant dans la documentation française que la description de la commande `\PuzzleThemes`.

Je ne suis pas certain qu'il faille franciser systématiquement les noms des commandes et des clés, surtout lorsque le nom est de l'anglais relativement simple. En l'occurrence, `Thickness`, `Scale`, `BgColors` (Bg pour background), `BorderColor`, `Labels`, `ScaleLabels`, `FontLabels` et `IconsColor` me semblent être assez compréhensibles et faciles à retenir (de plus, ce sont des concepts fréquemment rencontrés dans les documentations d'autres packages dont le manuel est exclusivement rédigé en anglais).

Toutefois, comme c'est désormais fait, gardons cela pour éviter une incompatibilité entre versions.

Je suggère que la documentation dans une langue donne le nom de la commande et des clés dans l'autre langue. Ainsi, nous lirions « `Thickness` (alias `Epaisseur`) ». 

Il faudrait aussi que la commande `\ThematicPuzzle` reconnaisse les clés en français et `\PuzzleThemes` reconnaisse les clés en anglais, si ce n'est pas trop compliqué à coder. Actuellement, la clé en anglais `IconsColor` dans `\PuzzleThemes` (nom en français) est simplement ignorée, sans générer d'erreur.

Toujours au niveau de la documentation, on lit par exemple : 

`CouleursFond` := couleur de fond (`vide` par défaut) ;

Présenté ainsi, `vide` peut être pris comme valeur légitime de « couleur » pour la clé `CouleursFond`. Je propose d'enlever la mise en forme du mot « vide » (de même pour « empty » en anglais).

Dans le dernier exemple de code, la couleur `teal!50!black` est employée. C'est une couleur subtilement distincte du noir (cela se voit sur de bons écrans, et si on prête attention, mais pas si on regarde très rapidement). La valeur `teal!75!black` me semble plus percutante sans dénaturer votre choix.

La couleur actuelle se trouve au centre. Ma suggestion se trouve au bas (je conserve le noir en haut, pour comparaison).

<img width="429" alt="image" src="https://github.com/cpierquet/thematicpuzzle/assets/9338576/53cab606-164d-4fda-85b9-34e85da5ef88">

Notons aussi que si l'on n'indique qu'une couleur de fond, comme ici : 

```tex
\PuzzleThemes[Epaisseur=2pt,Echelle=1.25, CouleursFond={yellow!10}, Labels={Probas,Stats,Python,Suites,Matrices},CouleurBord=brown, CouleurIcones=teal!75!black]{\ThemProbas,\ThemStats,\ThemPython,\ThemSuites,\ThemMatrices}
```

on obtient bien des fonds de la même couleur pour toutes les pièces (ce point est illustré dans le troisième exemple de la documentation dans la sous-section 2.4).

<img width="421" alt="image" src="https://github.com/cpierquet/thematicpuzzle/assets/9338576/0c5440e5-5d75-4276-a570-155577b9b42a">

Par contre, contrairement à ce qu'on pourrait espérer, ne mettre que 2 couleurs ne permet pas de générer une alternance : 

```tex
\PuzzleThemes[Epaisseur=2pt,Echelle=1.25, CouleursFond={yellow!10,orange!10}, Labels={Probas,Stats,Python,Suites,Matrices},CouleurBord=brown, CouleurIcones=teal!75!black]{\ThemProbas,\ThemStats,\ThemPython,\ThemSuites,\ThemMatrices}
```

produit (enfin, normalement, ça ne devrait pas générer une sortie vue le nombre d'erreurs dans le .log mais certains IDE de code LaTeX sont tolérants lors de la compilation) : 

<img width="417" alt="image" src="https://github.com/cpierquet/thematicpuzzle/assets/9338576/60fd3033-870a-4fb8-a898-4b5a92650309">

À moins que ce point puisse être géré, il faudrait préciser cette limitation dans la documentation (c'est-à-dire que le nombre de couleurs à indiquer doit être soit de 1, soit égal au nombre de décorations dans la liste des décorations donnée dans la commande `\ThematicPuzzle` ou `\PuzzleThemes`).

Bravo pour votre créativité et encore une fois un joli package.

Je n'ai pas voulu ouvrir plusieurs « issues », car tous ces points concernent la documentation, mais si vous préférez qu'à l'avenir je découpe en plusieurs éléments séparés si la situation se représente, je ferais comme cela vous arrange.

**Comment by cpierquet** [comment]
Merci pour les retours :-)

Concernant les versions francisées, c'est un choix de ma part de proposer des versions francophones complètes sur certains de mes packages, mais en conservant une version anglaise et une notice anglaise (pour certains je ne fais qu'une doc avec des sections spécifiques pour les clés [en]).
Sinon j'avais déjà envisagé de pouvoir mixer clés [en] et [fr] mais ce sont les booléens qui vont poser souci...
Pour les couleurs, je réfléchis à une solution pour répéter les couleurs dans le cas où le nombre ne serait pas suffisant, et également être plus précis dans la documentation :-)

Je note également les retours sur des précisions à apporter dans la doc :-)
